SystemOrganization addCategory: #MOPClientZone!
SystemOrganization addCategory: #'MOPClientZone-Controllers'!
SystemOrganization addCategory: #'MOPClientZone-Database'!
SystemOrganization addCategory: #'MOPClientZone-Entities'!
SystemOrganization addCategory: #'MOPClientZone-Manifest'!
SystemOrganization addCategory: #'MOPClientZone-Server'!
SystemOrganization addCategory: #'MOPClientZone-Services'!
